### PR TITLE
fix(router): query params not being saved

### LINKED ISSUE #1509: Preserving the existing queryParams on back navigation
### If there is no issue for your problem, tell us about it
Going back remove the existing queryParams of that page which should be preserved as the params

### Which platform(s) does your issue occur on?

iOS (Android untested, but suspect the behaviors will be the same), both emulator and device

### Please, provide the following version numbers that your issue occurs with:
from playground
```js
{
  "@angular/animations": "6.1.1",
  "@angular/common": "6.1.1",
  "@angular/compiler": "6.1.1",
  "@angular/core": "6.1.1",
  "@angular/forms": "6.1.1",
  "@angular/http": "6.1.1",
  "@angular/platform-browser": "6.1.1",
  "@angular/platform-browser-dynamic": "6.1.1",
  "@angular/router": "6.1.1",
  "kinvey-nativescript-sdk": "3.11.6",
  "nativescript-accelerometer": "2.0.1",
  "nativescript-angular": "6.1.0",
  "nativescript-background-http": "3.3.0",
  "nativescript-camera": "4.0.2",
  "nativescript-fresco": "4.0.0",
  "nativescript-geolocation": "4.3.0",
  "nativescript-intl": "3.0.0",
  "nativescript-iqkeyboardmanager": "1.3.0",
  "nativescript-social-share": "1.5.0",
  "nativescript-theme-core": "1.0.4",
  "nativescript-ui-autocomplete": "3.8.0",
  "nativescript-ui-calendar": "3.7.0",
  "nativescript-ui-chart": "3.7.0",
  "nativescript-ui-dataform": "3.6.2",
  "nativescript-ui-gauge": "3.6.0",
  "nativescript-ui-listview": "3.5.11",
  "nativescript-ui-sidedrawer": "4.2.1",
  "nativescript-vue": "1.3.1",
  "reflect-metadata": "0.1.12",
  "rxjs": "6.2.2",
  "tns-core-modules": "4.2.0",
  "zone.js": "0.8.26"
}
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
I've created a demo on playground which is a simple 3 pages app. 
The 3 pages are Home(`/home`), Page2(`/home/page2/:id?q`) and Page3(`/home/page3`)
On Page2, I have code logging the params and queryParams
```js
this.pageRoute.activatedRoute.pipe(
			switchMap((activatedRoute: ActivatedRoute) => activatedRoute.queryParams)
		).subscribe((params: Params) => {
			console.log('query.q: ', params.q);
			});


		this.pageRoute.activatedRoute.pipe(
			switchMap((activatedRoute: ActivatedRoute) => activatedRoute.params)
		).subscribe((params: Params) => {
			console.log('params.id: ', params.id);
		});
```

- On Home page (`/home`), go Page2(`/home/page2/whaterever?q=querys`)
- See console log `query.q: querys` `params.id: whatever`
- Go Page3(`/home/page3`)
- Go back to Page2
- See console log `query.q: undefined`

### Is there any code involved? 
https://play.nativescript.org/?template=play-ng&id=yEsgnU

### PR DESCRIPTION
**Pull request by edusperoni**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-angular/blob/master/DevelopmentWorkflow.md#running-the-tests
- [x] Tests for the changes are included.

## What is the current behavior?
Query parameters are not preserved when navigating back.

The router state consists only of `UrlSegmentGroup`, which does not store any query parameters.

## What is the new behavior?
The state now stores the QueryParams and properly restores them.

Fixes #1509.

-----
Please ignore the tests I've done in e2e, I'll remove them when work is done.

Tests are passing, additional tests needed for modal and params preservation

Possible alternative:
store `queryParams[]` in `NSLocationStrategy` (since the outlet itself does not have queryParams, but the page does) and push to it at every `pushState` and pop at every `popState`, but how would it work with replaceState?

### CODE REVIEW

**Comment by edusperoni** [comment]
After some testing, I believe this is ready for review (e2e changes need to be reverted before merge)

**Comment by lini** [comment]
test

**Comment by dtopuzov** [comment]
test

File: nativescript-angular/router/ns-location-strategy.ts [hunk 1]
```diff
@@ -604,15 +607,16 @@ export class NSLocationStrategy extends LocationStrategy {
...
         const isNewPage = outlet.states.length === 0;
         const lastState = outlet.states[outlet.states.length - 1];
         const equalStateUrls = outlet.containsTopState(currentSegmentGroup.toString());
 
         const locationState: LocationState = {
             segmentGroup: currentSegmentGroup,
             isRootSegmentGroup: false,
-            isPageNavigation: isNewPage
+            isPageNavigation: isNewPage,
+            queryParams: {...queryParams}
```
Comment (NathanWalker) [inline nativescript-angular/router/ns-location-strategy.ts:619]: May be best to use some protection here in case queryParams comes in null or undefined?
```
queryParams: { ...(queryParams || {}) }
```

File: nativescript-angular/router/ns-location-strategy.ts [hunk 2]
```diff
@@ -645,14 +649,15 @@ export class NSLocationStrategy extends LocationStrategy {
...
+    private createOutlet(outletKey: string, path: string, segmentGroup: any, parent: Outlet, modalNavigation?: number, queryParams: Params = {}): Outlet {
         const pathByOutlets = this.getPathByOutlets(segmentGroup);
         const newOutlet = new Outlet(outletKey, path, pathByOutlets, modalNavigation);
 
         const locationState: LocationState = {
             segmentGroup: segmentGroup,
             isRootSegmentGroup: false,
-            isPageNavigation: true // It is a new OutletNode.
+            isPageNavigation: true, // It is a new OutletNode.
+            queryParams: {...queryParams}
```
Comment (NathanWalker) [inline nativescript-angular/router/ns-location-strategy.ts:660]: Same here:
```
queryParams: { ...(queryParams || {}) }
```

**Comment by NathanWalker** [comment]
Thank you for the contribution @edusperoni 👍
