### PR TITLE
FIX: ListView infinite change detection 

### LINKED ISSUE #262: Critical - Memory and cpu usage.
According xcode, memory usage for a very simple app (Just a listview) is around 100MB, and cpu is 40% (1 thread is maxed out).

The weird thing is that cpu usage drops as soon as I scroll (and hold) the ListView

image

image

image

If I open a second listview, cpu jumps from 40% to 60%. Press/hold still brings it back to 0
image

image

### PR DESCRIPTION
**Pull request by vakrilov**
Fixes:
 - Infinite ChangeDetection when `ListView` is used.
 - Trigger change detection on each item when it is loading.

Resolves #262

### CODE REVIEW

File: nativescript-angular/directives/list-view-comp.ts [hunk 1]
```diff
@@ -73,21 +76,26 @@ export class ListViewComponent {
...
 
-    private timerId: number;
-    private doCheckDelay = 5;
-                
     constructor(private _elementRef: ElementRef,
-                private _iterableDiffers: IterableDiffers,
-                private _cdr: ChangeDetectorRef) {
+        private _iterableDiffers: IterableDiffers,
+        private _cdr: ChangeDetectorRef,
+        private _zone: NgZone) {
```
Comment (hdeshev) [inline nativescript-angular/directives/list-view-comp.ts]: `_zone` seems to be unused here.

File: nativescript-angular/directives/list-view-comp.ts [hunk 2]
```diff
@@ -73,21 +76,26 @@ export class ListViewComponent {
             needDiffer = false;
         }
         if (needDiffer && !this._differ && isListLikeIterable(value)) {
-            this._differ = this._iterableDiffers.find(this._items).create(this._cdr, (index, item) => { return item;});
+            this._differ = this._iterableDiffers.find(this._items).create(this._cdr, (index, item) => { return item; });
         }
+
+        // this._cdr.detach();
```
Comment (hdeshev) [inline nativescript-angular/directives/list-view-comp.ts]: Probably forgotten to delete the commented out line.
